# Generated by Django 4.2.6 on 2025-03-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=20, unique=True)),
                ('source_identifier', models.CharField(max_length=100)),
                ('vuln_status', models.CharField(max_length=50)),
                ('published_date', models.DateTimeField()),
                ('last_modified_date', models.DateTimeField()),
                ('evaluator_comment', models.TextField(blank=True, null=True)),
                ('evaluator_solution', models.TextField(blank=True, null=True)),
                ('evaluator_impact', models.TextField(blank=True, null=True)),
                ('cisa_exploit_add', models.DateField(blank=True, null=True)),
                ('cisa_action_due', models.DateField(blank=True, null=True)),
                ('cisa_required_action', models.TextField(blank=True, null=True)),
                ('cisa_vulnerability_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cve_tags', models.JSONField(blank=True, null=True)),
                ('descriptions', models.JSONField()),
                ('references', models.JSONField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('weaknesses', models.JSONField(blank=True, null=True)),
                ('configurations', models.JSONField(blank=True, null=True)),
                ('vendor_comments', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
