# Generated by Django 4.2.6 on 2025-03-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('results', models.JSONField(default=list)),
                ('hosting_info', models.JSONField(default=dict)),
                ('passive_results', models.JSONField(default=list)),
            ],
        ),
    ]
