# Generated by Django 4.2.6 on 2025-03-04 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cve',
            old_name='tags',
            new_name='cve_tags',
        ),
    ]
