# Generated by Django 4.2.6 on 2025-04-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zap', '0002_scandata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('messages', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
    ]
