# Generated by Django 4.2.6 on 2025-02-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VulnerabilitySignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the vulnerability signature', max_length=255, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the vulnerability')),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], help_text='Severity level of the vulnerability', max_length=10)),
                ('affected_component', models.CharField(help_text='Component or system affected by the vulnerability', max_length=255)),
                ('pattern', models.TextField(help_text='Regex or string pattern for detecting the vulnerability')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
